[project]
name = "xrequest"
version = "0.0.4"
description = "Simple httpx for lazy people"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name = "Reollinos"}]
dependencies = []

[project.urls]
Homepage = "https://github.com/Reollinos/xrequest"
Repository = "https://github.com/Reollinos/xrequest"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"